"""Message

Revision ID: 14470319b98b
Revises: 9a6f525d8e29
Create Date: 2019-02-19 11:23:28.761378

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '14470319b98b'
down_revision = '9a6f525d8e29'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blog',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('date_posted', sa.DateTime(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('users', sa.Column('blog_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'blog', ['blog_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'blog_id')
    op.drop_table('blog')
    # ### end Alembic commands ###
